    .common
    
    .export _plot_char
    .export _scroll_down
    .export _scroll_up
    .export _cursor_on
    .export _cursor_off
    .export _cursor_disable
    .export _clear_lines
    .export _clear_across
    .export _do_beep
    .export _vtattr_notify
    .export _vtattr_cap

#include "kernelu.def"

vt_start:
    push af
    ld a, IO_SEL_TTY
    out (IO_SEL_REG), a
    pop af
    ret

vt_wait:
    push af
vt_wait_loop:
    in a, (TTY_BUSY)
    or a
    jr nz, vt_wait_loop
    pop af
    ret    

    ; Expects X in D, Y in E
vt_set_pos:
    push af
    ; Set X
    call vt_wait
    ld a, d
    out (TTY_XPOS), a
    ; Set Y
    call vt_wait
    ld a, e
    out (TTY_YPOS), a
    pop af
    ret

_vtattr_cap:
    .byte 1     ; Inverse video

_vtattr_notify:
    call vt_start
    ld a, (_vtattr)
    and 1
    out (TTY_INVERSE), a
    ld a, (_vtink)
    out (TTY_INK), a
    ld a, (_vtpaper)
    out (TTY_PAPER), a
    ret

_do_beep:
    ret


_clear_across:
    call vt_start
   
    ld hl, #6
    add hl, sp
    ld a,(hl)
    dec hl
    dec hl
    ld d,(hl)
    dec hl
    dec hl
    ld e,(hl)

    or a
    ret z
    ld b, a ;
    ; Y in E, X in D, count in B 
    call vt_set_pos

clear_across_loop:
    call vt_wait
    ld a, #' '
    out (TTY_OUT), a ; output space
    inc d
    ld a, d
    out (TTY_XPOS), a ; increase X
    djnz clear_across_loop
clear_across_done:
    ret

_clear_lines:
    push bc
    ld hl, #6
    add hl, sp
    ld b,(hl) ; count in B
    dec hl
    dec hl
    ld e,(hl)

    call vt_start

    ; Move cursor
    ld d, 0
    call vt_set_pos
 
clear_lines_loop:
    call vt_set_pos
    call vt_wait
    ; Clear to EOL
    ld a, 1
    out (TTY_CL_EOL), a
    ; Next line
    inc e
    ld a, e
    out (TTY_YPOS), a
    djnz clear_lines_loop
    
    pop bc 

    ret

_scroll_down:
    call vt_start
    call vt_wait
    ld a, 0x01
    out (TTY_SCR_D), a
    ret    

_scroll_up:
    call vt_start
    call vt_wait
    ld a, 0x01
    out (TTY_SCR_U), a
    ret    


_cursor_on:
    ld hl, 2
    add hl, sp
    ld e, (hl)
    inc hl
    inc hl
    ld d, (hl)

    call vt_start

    call vt_set_pos

    call vt_wait
    ld a, 0x01
    out (TTY_CUR_VIS), a
    ret


_cursor_off:
_cursor_disable:
    call vt_start
    call vt_wait
    ld a, 0x00
    out (TTY_CUR_VIS), a
    ret

_plot_char:
    call vt_start
 
    ld hl, #6
    add hl, sp
    ld a,(hl)
    dec hl
    dec hl
    ld d,(hl)
    dec hl
    dec hl
    ld e,(hl)

    ; Y is in E, X in D and char in A
    
    call vt_set_pos
    ;call vt_charout
    out (TTY_OUT), a
    ret    
