#!/bin/sh
#
#	Generate the z80sio helpers using the template
#
cd $FUZIX_ROOT
cat Kernel/build/serial.hdr
template <Kernel/dev/z80sio.tmpl a ".abs\n.org 0x0100" ".commondata" SIOA_C SIOA_D \
	reti "" "" ".common"
template <Kernel/dev/z80sio.tmpl b ".abs\n.org 0x0200" ".commondata" SIOB_C SIOB_D \
	reti "ld (sio_sp),sp\nld sp,istack_top\ncall map_save_kernel" \
	"call map_restore\nld sp,(sio_sp)" ".common"
