        ; startup code
	.code
init:
        di
        ld	sp, kstack_top

        ; move the common memory where it belongs    
        ld	hl, __bss
        ld	de, __common
        ld	bc,__common_size
        ldir
	; FIXME - commondata ??
        ; and the discard
	; should use lddr ?
        ld	de, __discard
        ld	bc, __discard_size
        ldir
        ; then zero the data area
        ld	hl, __bss
        ld	de, __bss + 1
        ld	bc, __bss_size - 1
        ld	(hl), 0
        ldir

        ; Configure memory map
        call	init_early

        ; Hardware setup
        call	init_hardware

        ; Call the C main routine
        call	_fuzix_main
    
        ; fuzix_main() shouldn't return, but if it does...
        di
stop:   halt
        jr	stop
